"""Constants for Meshtastic application port numbers."""

TEXT_MESSAGE_APP = "TEXT_MESSAGE_APP"
POSITION_APP = "POSITION_APP"
NODEINFO_APP = "NODEINFO_APP"
ROUTING_APP = "ROUTING_APP"
ADMIN_APP = "ADMIN_APP"
TELEMETRY_APP = "TELEMETRY_APP"
